/*
 * Auto-generated by Frida. Please modify to match the signature of _Z36register_android_media_MediaProfilesP7_JNIEnv.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_Z36register_android_media_MediaProfilesP7_JNIEnv()');
  },

  onLeave(log, retval, state) {
  }
});
