/*
 * Auto-generated by Frida. Please modify to match the signature of OPENSSL_secure_malloc.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`OPENSSL_secure_malloc(num=${args[0]})`);
  },

  onLeave(log, retval, state) {
  }
});
