/*
 * Auto-generated by Frida. Please modify to match the signature of OPENSSL_strlcat.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`OPENSSL_strlcat(dst="${args[0].readUtf8String()}", src="${args[1].readUtf8String()}", size=${args[2]})`);
  },

  onLeave(log, retval, state) {
  }
});
