/*
 * Auto-generated by Frida. Please modify to match the signature of OPENSSL_strcasecmp.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`OPENSSL_strcasecmp(s1="${args[0].readUtf8String()}", s2="${args[1].readUtf8String()}")`);
  },

  onLeave(log, retval, state) {
  }
});
