/*
 * Auto-generated by Frida. Please modify to match the signature of OPENSSL_gmtime_diff.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`OPENSSL_gmtime_diff(pday=${args[0]}, psec=${args[1]}, from=${args[2]}, to=${args[3]})`);
  },

  onLeave(log, retval, state) {
  }
});
