/*
 * Auto-generated by Frida. Please modify to match the signature of OPENSSL_realloc.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`OPENSSL_realloc(addr=${args[0]}, num=${args[1]})`);
  },

  onLeave(log, retval, state) {
  }
});
