/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android12AudioProfile14setSampleRatesERKNSt3__13setIjNS1_4lessIjEENS1_9allocatorIjEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android12AudioProfile14setSampleRatesERKNSt3__13setIjNS1_4lessIjEENS1_9allocatorIjEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
