/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android21populateAudioProfilesERKNSt3__18multimapI14audio_format_tNS0_4pairINS0_3setIjNS0_4lessIjEENS0_9allocatorIjEEEENS4_I20audio_channel_mask_tNS5_ISA_EENS7_ISA_EEEEEENS5_IS2_EENS7_INS3_IKS2_SE_EEEEEES2_SD_S9_P13audio_profilePjj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android21populateAudioProfilesERKNSt3__18multimapI14audio_format_tNS0_4pairINS0_3setIjNS0_4lessIjEENS0_9allocatorIjEEEENS4_I20audio_channel_mask_tNS5_ISA_EENS7_ISA_EEEEEENS5_IS2_EENS7_INS3_IKS2_SE_EEEEEES2_SD_S9_P13audio_profilePjj()');
  },

  onLeave(log, retval, state) {
  }
});
