/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android12AudioProfile14fromParcelableERKNSt3__14pairINS_5media5audio6common12AudioProfileENS3_15AudioProfileSysEEEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android12AudioProfile14fromParcelableERKNSt3__14pairINS_5media5audio6common12AudioProfileENS3_15AudioProfileSysEEEb()');
  },

  onLeave(log, retval, state) {
  }
});
