/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android30legacy2aidl_AudioProfileVectorERKNS_18AudioProfileVectorEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android30legacy2aidl_AudioProfileVectorERKNS_18AudioProfileVectorEb()');
  },

  onLeave(log, retval, state) {
  }
});
