/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android30aidl2legacy_AudioProfileVectorERKNSt3__14pairINS0_6vectorINS_5media5audio6common12AudioProfileENS0_9allocatorIS6_EEEENS2_INS3_15AudioProfileSysENS7_ISA_EEEEEEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android30aidl2legacy_AudioProfileVectorERKNSt3__14pairINS0_6vectorINS_5media5audio6common12AudioProfileENS0_9allocatorIS6_EEEENS2_INS3_15AudioProfileSysENS7_ISA_EEEEEEb()');
  },

  onLeave(log, retval, state) {
  }
});
