/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android18AudioProfileVector3addERKNS_2spINS_12AudioProfileEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android18AudioProfileVector3addERKNS_2spINS_12AudioProfileEEE()');
  },

  onLeave(log, retval, state) {
  }
});
