/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android12AudioProfile11setChannelsERKNSt3__13setI20audio_channel_mask_tNS1_4lessIS3_EENS1_9allocatorIS3_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android12AudioProfile11setChannelsERKNSt3__13setI20audio_channel_mask_tNS1_4lessIS3_EENS1_9allocatorIS3_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
