/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android12AudioProfile17createFullDynamicE14audio_format_t.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android12AudioProfile17createFullDynamicE14audio_format_t()');
  },

  onLeave(log, retval, state) {
  }
});
