/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android12AudioProfileC2E14audio_format_tRKNSt3__13setI20audio_channel_mask_tNS2_4lessIS4_EENS2_9allocatorIS4_EEEERKNS3_IjNS5_IjEENS7_IjEEEE26audio_encapsulation_type_t.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android12AudioProfileC2E14audio_format_tRKNSt3__13setI20audio_channel_mask_tNS2_4lessIS4_EENS2_9allocatorIS4_EEEERKNS3_IjNS5_IjEENS7_IjEEEE26audio_encapsulation_type_t()');
  },

  onLeave(log, retval, state) {
  }
});
