/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android12AudioProfileC1E14audio_format_t20audio_channel_mask_tj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android12AudioProfileC1E14audio_format_t20audio_channel_mask_tj()');
  },

  onLeave(log, retval, state) {
  }
});
