/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK7android18AudioProfileVector8containsERKNS_2spINS_12AudioProfileEEEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK7android18AudioProfileVector8containsERKNS_2spINS_12AudioProfileEEEb()');
  },

  onLeave(log, retval, state) {
  }
});
