/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3art22ProfileCompilationInfo19GenerateTestProfileEiRNSt3__16vectorINS1_10unique_ptrIKNS_7DexFileENS1_14default_deleteIS5_EEEENS1_9allocatorIS8_EEEEttj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3art22ProfileCompilationInfo19GenerateTestProfileEiRNSt3__16vectorINS1_10unique_ptrIKNS_7DexFileENS1_14default_deleteIS5_EEEENS1_9allocatorIS8_EEEEttj()');
  },

  onLeave(log, retval, state) {
  }
});
