/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3art22ProfileCompilationInfo11DexFileData13WriteClassSetERNS0_10SafeBufferERKNSt3__13setINS_3dex9TypeIndexENS4_4lessIS7_EENS_21ArenaAllocatorAdapterIS7_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3art22ProfileCompilationInfo11DexFileData13WriteClassSetERNS0_10SafeBufferERKNSt3__13setINS_3dex9TypeIndexENS4_4lessIS7_EENS_21ArenaAllocatorAdapterIS7_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
