/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3art22ProfileCompilationInfo17VerifyProfileDataERKNSt3__16vectorIPKNS_7DexFileENS1_9allocatorIS5_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3art22ProfileCompilationInfo17VerifyProfileDataERKNSt3__16vectorIPKNS_7DexFileENS1_9allocatorIS5_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
