/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3artlsERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEENS_22ProfileCompilationInfo18DexReferenceDumperE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3artlsERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEENS_22ProfileCompilationInfo18DexReferenceDumperE()');
  },

  onLeave(log, retval, state) {
  }
});
