/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3art22ProfileCompilationInfo11DexFileData11SkipClassesERNS0_10SafeBufferEPNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3art22ProfileCompilationInfo11DexFileData11SkipClassesERNS0_10SafeBufferEPNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
