/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3art22ProfileCompilationInfo11DexFileData11ReadClassesERNS0_10SafeBufferERKNS_15dchecked_vectorItNSt3__19allocatorItEEEEPNS5_12basic_stringIcNS5_11char_traitsIcEENS6_IcEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3art22ProfileCompilationInfo11DexFileData11ReadClassesERNS0_10SafeBufferERKNS_15dchecked_vectorItNSt3__19allocatorItEEEEPNS5_12basic_stringIcNS5_11char_traitsIcEENS6_IcEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
