/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3art15ProfileBootInfo3AddEPKNS_7DexFileEj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3art15ProfileBootInfo3AddEPKNS_7DexFileEj()');
  },

  onLeave(log, retval, state) {
  }
});
