/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3art22ProfileCompilationInfo29GetProfileDexFileAugmentedKeyERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS0_23ProfileSampleAnnotationE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3art22ProfileCompilationInfo29GetProfileDexFileAugmentedKeyERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS0_23ProfileSampleAnnotationE()');
  },

  onLeave(log, retval, state) {
  }
});
