/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3art22ProfileCompilationInfo10OpenSourceEiPNSt3__110unique_ptrINS0_13ProfileSourceENS1_14default_deleteIS3_EEEEPNS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3art22ProfileCompilationInfo10OpenSourceEiPNSt3__110unique_ptrINS0_13ProfileSourceENS1_14default_deleteIS3_EEEEPNS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
