/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3art22ProfileCompilationInfo18ReadMethodsSectionERNS0_13ProfileSourceERKNS0_15FileSectionInfoERKNS_15dchecked_vectorItNSt3__19allocatorItEEEESC_PNS7_12basic_stringIcNS7_11char_traitsIcEENS8_IcEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3art22ProfileCompilationInfo18ReadMethodsSectionERNS0_13ProfileSourceERKNS0_15FileSectionInfoERKNS_15dchecked_vectorItNSt3__19allocatorItEEEESC_PNS7_12basic_stringIcNS7_11char_traitsIcEENS8_IcEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
