/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3art22ProfileCompilationInfo19ReadDexFilesSectionERNS0_13ProfileSourceERKNS0_15FileSectionInfoERKNSt3__18functionIFbRKNS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEEjEEEPNS_15dchecked_vectorItNSB_ItEEEEPSD_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3art22ProfileCompilationInfo19ReadDexFilesSectionERNS0_13ProfileSourceERKNS0_15FileSectionInfoERKNSt3__18functionIFbRKNS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEEjEEEPNS_15dchecked_vectorItNSB_ItEEEEPSD_()');
  },

  onLeave(log, retval, state) {
  }
});
