/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK3art22ProfileCompilationInfo11DexFileData14GetHotnessInfoEj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK3art22ProfileCompilationInfo11DexFileData14GetHotnessInfoEj()');
  },

  onLeave(log, retval, state) {
  }
});
