/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK3art22ProfileCompilationInfo8DumpInfoERKNSt3__16vectorIPKNS_7DexFileENS1_9allocatorIS5_EEEEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK3art22ProfileCompilationInfo8DumpInfoERKNSt3__16vectorIPKNS_7DexFileENS1_9allocatorIS5_EEEEb()');
  },

  onLeave(log, retval, state) {
  }
});
