/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK3art22ProfileCompilationInfo16GetMethodHotnessERKNS_15MethodReferenceERKNS0_23ProfileSampleAnnotationE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK3art22ProfileCompilationInfo16GetMethodHotnessERKNS_15MethodReferenceERKNS0_23ProfileSampleAnnotationE()');
  },

  onLeave(log, retval, state) {
  }
});
