/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK3art22ProfileCompilationInfo20GetClassesAndMethodsERKNS_7DexFileEPNSt3__13setINS_3dex9TypeIndexENS4_4lessIS7_EENS4_9allocatorIS7_EEEEPNS5_ItNS8_ItEENSA_ItEEEESH_SH_RKNS0_23ProfileSampleAnnotationE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK3art22ProfileCompilationInfo20GetClassesAndMethodsERKNS_7DexFileEPNSt3__13setINS_3dex9TypeIndexENS4_4lessIS7_EENS4_9allocatorIS7_EEEEPNS5_ItNS8_ItEENSA_ItEEEESH_SH_RKNS0_23ProfileSampleAnnotationE()');
  },

  onLeave(log, retval, state) {
  }
});
