/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android8C2Mapper24GetHdrProfileLevelMapperENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android8C2Mapper24GetHdrProfileLevelMapperENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEb()');
  },

  onLeave(log, retval, state) {
  }
});
