/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android8C2Mapper18ProfileLevelMapper12mapHdrFormatEiPN8C2Config12hdr_format_tE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android8C2Mapper18ProfileLevelMapper12mapHdrFormatEiPN8C2Config12hdr_format_tE()');
  },

  onLeave(log, retval, state) {
  }
});
