/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android11AudioSystem30getDirectProfilesForAttributesEPK18audio_attributes_tPNSt3__16vectorI13audio_profileNS4_9allocatorIS6_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android11AudioSystem30getDirectProfilesForAttributesEPK18audio_attributes_tPNSt3__16vectorI13audio_profileNS4_9allocatorIS6_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
