/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8ultrahdr9IccHelper15writeIccProfileENS_26ultrahdr_transfer_functionENS_20ultrahdr_color_gamutE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8ultrahdr9IccHelper15writeIccProfileENS_26ultrahdr_transfer_functionENS_20ultrahdr_color_gamutE()');
  },

  onLeave(log, retval, state) {
  }
});
