/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android5media20BpAudioPolicyService30getDirectProfilesForAttributesERKNS0_5audio6common15AudioAttributesEPNSt3__16vectorINS3_12AudioProfileENS7_9allocatorIS9_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android5media20BpAudioPolicyService30getDirectProfilesForAttributesERKNS0_5audio6common15AudioAttributesEPNSt3__16vectorINS3_12AudioProfileENS7_9allocatorIS9_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
