/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android13MediaProfiles14findTagForNameEPKNS0_12NameToTagMapEmPKc.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android13MediaProfiles14findTagForNameEPKNS0_12NameToTagMapEmPKc()');
  },

  onLeave(log, retval, state) {
  }
});
