/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3sce3rts15SignalingClient4Impl14getProfileInfoENSt6__ndk18functionIFviEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3sce3rts15SignalingClient4Impl14getProfileInfoENSt6__ndk18functionIFviEEE()');
  },

  onLeave(log, retval, state) {
  }
});
