/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS0_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS1_FvRKT_E.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS0_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS1_FvRKT_E()');
  },

  onLeave(log, retval, state) {
  }
});
