/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3sce5party24GameTitleInfoTransceiver35onMyGameTitleInfoOnPsnServerUpdatedERKNS0_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3sce5party24GameTitleInfoTransceiver35onMyGameTitleInfoOnPsnServerUpdatedERKNS0_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedE()');
  },

  onLeave(log, retval, state) {
  }
});
