/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNKSt6__ndk110__function6__funcIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUliNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE_NSC_ISF_EEFviRKSE_EE7__cloneEPNS0_6__baseISJ_EE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNKSt6__ndk110__function6__funcIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUliNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE_NSC_ISF_EEFviRKSE_EE7__cloneEPNS0_6__baseISJ_EE()');
  },

  onLeave(log, retval, state) {
  }
});
