/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNKSt6__ndk110__function6__funcIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEblmdSG_NS9_14adl_serializerEEEE_NSG_ISL_EEFvSK_EE6targetERKSt9type_info.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNKSt6__ndk110__function6__funcIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEblmdSG_NS9_14adl_serializerEEEE_NSG_ISL_EEFvSK_EE6targetERKSt9type_info()');
  },

  onLeave(log, retval, state) {
  }
});
