/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk128__invoke_void_return_wrapperIvE6__callIJRZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUliNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE_iRKSF_EEEvDpOT_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk128__invoke_void_return_wrapperIvE6__callIJRZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUliNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE_iRKSF_EEEvDpOT_()');
  },

  onLeave(log, retval, state) {
  }
});
