/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk122__compressed_pair_elemINS_22__allocator_destructorINS_9allocatorINS_10__function6__funcIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS6_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS7_FvRKT_EEUlP6CEventE_NS2_ISH_EEFvSG_EEEEEEELi1ELb0EEC2ISM_vEEOSA_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk122__compressed_pair_elemINS_22__allocator_destructorINS_9allocatorINS_10__function6__funcIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS6_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS7_FvRKT_EEUlP6CEventE_NS2_ISH_EEFvSG_EEEEEEELi1ELb0EEC2ISM_vEEOSA_()');
  },

  onLeave(log, retval, state) {
  }
});
