/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk122__compressed_pair_elemINS_9allocatorIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS1_IcEEEEblmdS1_NS9_14adl_serializerEEEE_EELi1ELb1EEC2IJRKSL_EJLm0EEEENS_21piecewise_construct_tENS_5tupleIJDpT_EEENS_15__tuple_indicesIJXspT0_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk122__compressed_pair_elemINS_9allocatorIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS1_IcEEEEblmdS1_NS9_14adl_serializerEEEE_EELi1ELb1EEC2IJRKSL_EJLm0EEEENS_21piecewise_construct_tENS_5tupleIJDpT_EEENS_15__tuple_indicesIJXspT0_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
