/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk18functionIFviRKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEEEC2IZN3sce3rts15SignalingClient4Impl14getProfileInfoENS0_IFviEEEEUliS6_E_vEET_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk18functionIFviRKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEEEC2IZN3sce3rts15SignalingClient4Impl14getProfileInfoENS0_IFviEEEEUliS6_E_vEET_()');
  },

  onLeave(log, retval, state) {
  }
});
