/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk128__invoke_void_return_wrapperIvE6__callIJRZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEblmdSH_NSA_14adl_serializerEEEE_SL_EEEvDpOT_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk128__invoke_void_return_wrapperIvE6__callIJRZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEblmdSH_NSA_14adl_serializerEEEE_SL_EEEvDpOT_()');
  },

  onLeave(log, retval, state) {
  }
});
