/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk18functionIFvP6CEventEEC2IZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS7_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS8_FvRKT_EEUlS2_E_vEESB_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk18functionIFvP6CEventEEC2IZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS7_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS8_FvRKT_EEUlS2_E_vEESB_()');
  },

  onLeave(log, retval, state) {
  }
});
