/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk19allocatorINS_10__function6__funcIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS0_IcEEEEblmdS0_NSA_14adl_serializerEEEE_NS0_ISL_EEFvSK_EEEEC2ISL_EERKNS0_IT_EE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk19allocatorINS_10__function6__funcIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS0_IcEEEEblmdS0_NSA_14adl_serializerEEEE_NS0_ISL_EEFvSK_EEEEC2ISL_EERKNS0_IT_EE()');
  },

  onLeave(log, retval, state) {
  }
});
