/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk19allocatorINS_10__function6__funcIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS4_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS5_FvRKT_EEUlP6CEventE_NS0_ISF_EEFvSE_EEEEC2ISF_EERKNS0_IS8_EE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk19allocatorINS_10__function6__funcIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS4_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS5_FvRKT_EEUlP6CEventE_NS0_ISF_EEFvSE_EEEEC2ISF_EERKNS0_IS8_EE()');
  },

  onLeave(log, retval, state) {
  }
});
