/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk117__compressed_pairIPNS_10__function6__funcIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEblmdSH_NSA_14adl_serializerEEEE_NSH_ISM_EEFvSL_EEENS_22__allocator_destructorINSH_ISP_EEEEEC2IRSQ_ST_EEOT_OT0_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk117__compressed_pairIPNS_10__function6__funcIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEblmdSH_NSA_14adl_serializerEEEE_NSH_ISM_EEFvSL_EEENS_22__allocator_destructorINSH_ISP_EEEEEC2IRSQ_ST_EEOT_OT0_()');
  },

  onLeave(log, retval, state) {
  }
});
