/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk110unique_ptrINS_10__function6__funcIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS4_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS5_FvRKT_EEUlP6CEventE_NS_9allocatorISF_EEFvSE_EEENS_22__allocator_destructorINSG_ISJ_EEEEEC2ILb1EvEEPSJ_NS_16__dependent_typeINS_27__unique_ptr_deleter_sfinaeISM_EEXT_EE20__good_rval_ref_typeE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk110unique_ptrINS_10__function6__funcIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS4_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS5_FvRKT_EEUlP6CEventE_NS_9allocatorISF_EEFvSE_EEENS_22__allocator_destructorINSG_ISJ_EEEEEC2ILb1EvEEPSJ_NS_16__dependent_typeINS_27__unique_ptr_deleter_sfinaeISM_EEXT_EE20__good_rval_ref_typeE()');
  },

  onLeave(log, retval, state) {
  }
});
