/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk110__function12__value_funcIFvP6CEventEEC2IZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS8_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS9_FvRKT_EEUlS3_E_vEEOSC_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk110__function12__value_funcIFvP6CEventEEC2IZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS8_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS9_FvRKT_EEUlS3_E_vEEOSC_()');
  },

  onLeave(log, retval, state) {
  }
});
