/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk117__compressed_pairIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS2_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS3_FvRKT_EEUlP6CEventE_NS_9allocatorISD_EEEC2IJRKSD_EJRKSF_EEENS_21piecewise_construct_tENS_5tupleIJDpT_EEENSN_IJDpT0_EEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk117__compressed_pairIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS2_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS3_FvRKT_EEUlP6CEventE_NS_9allocatorISD_EEEC2IJRKSD_EJRKSF_EEENS_21piecewise_construct_tENS_5tupleIJDpT_EEENSN_IJDpT0_EEE()');
  },

  onLeave(log, retval, state) {
  }
});
