/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk128__invoke_void_return_wrapperIvE6__callIJRZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS4_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS5_FvRKT_EEUlP6CEventE_SE_EEEvDpOT_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk128__invoke_void_return_wrapperIvE6__callIJRZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS4_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS5_FvRKT_EEUlP6CEventE_SE_EEEvDpOT_()');
  },

  onLeave(log, retval, state) {
  }
});
