/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk112__tuple_leafILm0ERKZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS2_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS3_FvRKT_EEUlP6CEventE_Lb0EEC2ISF_vEEOS6_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk112__tuple_leafILm0ERKZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS2_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS3_FvRKT_EEUlP6CEventE_Lb0EEC2ISF_vEEOS6_()');
  },

  onLeave(log, retval, state) {
  }
});
