/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk19allocatorIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS2_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS3_FvRKT_EEUlP6CEventE_EC2INS_10__function6__funcISD_SE_FvSC_EEEEERKNS0_IS6_EE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk19allocatorIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS2_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS3_FvRKT_EEUlP6CEventE_EC2INS_10__function6__funcISD_SE_FvSC_EEEEERKNS0_IS6_EE()');
  },

  onLeave(log, retval, state) {
  }
});
