/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk122__compressed_pair_elemIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS2_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS3_FvRKT_EEUlP6CEventE_Li0ELb0EEC2IJRKSD_EJLm0EEEENS_21piecewise_construct_tENS_5tupleIJDpT_EEENS_15__tuple_indicesIJXspT0_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk122__compressed_pair_elemIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS2_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS3_FvRKT_EEUlP6CEventE_Li0ELb0EEC2IJRKSD_EJLm0EEEENS_21piecewise_construct_tENS_5tupleIJDpT_EEENS_15__tuple_indicesIJXspT0_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
