/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk112__tuple_implINS_15__tuple_indicesIJLm0EEEEJRKNS_9allocatorIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS3_IcEEEEblmdS3_NSB_14adl_serializerEEEE_EEEEC2IJLm0EEJSP_EJEJEJSP_EEENS1_IJXspT_EEEENS_13__tuple_typesIJDpT0_EEENS1_IJXspT1_EEEENST_IJDpT2_EEEDpOT3_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk112__tuple_implINS_15__tuple_indicesIJLm0EEEEJRKNS_9allocatorIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS3_IcEEEEblmdS3_NSB_14adl_serializerEEEE_EEEEC2IJLm0EEJSP_EJEJEJSP_EEENS1_IJXspT_EEEENS_13__tuple_typesIJDpT0_EEENS1_IJXspT1_EEEENST_IJDpT2_EEEDpOT3_()');
  },

  onLeave(log, retval, state) {
  }
});
