/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk117__compressed_pairIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEblmdSF_NS8_14adl_serializerEEEE_NSF_ISK_EEEC2IJRKSK_EJOSL_EEENS_21piecewise_construct_tENS_5tupleIJDpT_EEENSS_IJDpT0_EEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk117__compressed_pairIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEblmdSF_NS8_14adl_serializerEEEE_NSF_ISK_EEEC2IJRKSK_EJOSL_EEENS_21piecewise_construct_tENS_5tupleIJDpT_EEENSS_IJDpT0_EEE()');
  },

  onLeave(log, retval, state) {
  }
});
