/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk15tupleIJRKNS_9allocatorIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS1_IcEEEEblmdS1_NS9_14adl_serializerEEEE_EEEEC2ILb1ELb0EEESN_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk15tupleIJRKNS_9allocatorIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS1_IcEEEEblmdS1_NS9_14adl_serializerEEEE_EEEEC2ILb1ELb0EEESN_()');
  },

  onLeave(log, retval, state) {
  }
});
