/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk110__function12__value_funcIFvN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEblmdS9_NS2_14adl_serializerEEEEEC2IZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlSD_E_vEEOT_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk110__function12__value_funcIFvN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEblmdS9_NS2_14adl_serializerEEEEEC2IZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlSD_E_vEEOT_()');
  },

  onLeave(log, retval, state) {
  }
});
