/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk122__compressed_pair_elemIPNS_10__function6__funcIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS4_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS5_FvRKT_EEUlP6CEventE_NS_9allocatorISF_EEFvSE_EEELi0ELb0EEC2IRSK_vEEOS8_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk122__compressed_pair_elemIPNS_10__function6__funcIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS4_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS5_FvRKT_EEUlP6CEventE_NS_9allocatorISF_EEFvSE_EEELi0ELb0EEC2IRSK_vEEOS8_()');
  },

  onLeave(log, retval, state) {
  }
});
