/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk117__compressed_pairIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUliNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE_NSB_ISE_EEEC2IJRKSE_EJOSF_EEENS_21piecewise_construct_tENS_5tupleIJDpT_EEENSM_IJDpT0_EEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk117__compressed_pairIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUliNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE_NSB_ISE_EEEC2IJRKSE_EJOSF_EEENS_21piecewise_construct_tENS_5tupleIJDpT_EEENSM_IJDpT0_EEE()');
  },

  onLeave(log, retval, state) {
  }
});
