/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk117__compressed_pairIPNS_10__function6__funcIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS4_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS5_FvRKT_EEUlP6CEventE_NS_9allocatorISF_EEFvSE_EEENS_22__allocator_destructorINSG_ISJ_EEEEEC2IRSK_SN_EEOS8_OT0_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk117__compressed_pairIPNS_10__function6__funcIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS4_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS5_FvRKT_EEUlP6CEventE_NS_9allocatorISF_EEFvSE_EEENS_22__allocator_destructorINSG_ISJ_EEEEEC2IRSK_SN_EEOS8_OT0_()');
  },

  onLeave(log, retval, state) {
  }
});
