/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk18functionIFvN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEblmdS8_NS1_14adl_serializerEEEEEC2IZN3sce3rts15SignalingClient4Impl14getProfileInfoENS0_IFviEEEEUlSC_E_vEET_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk18functionIFvN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEblmdS8_NS1_14adl_serializerEEEEEC2IZN3sce3rts15SignalingClient4Impl14getProfileInfoENS0_IFviEEEEUlSC_E_vEET_()');
  },

  onLeave(log, retval, state) {
  }
});
