/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk15tupleIJOZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS2_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS3_FvRKT_EEUlP6CEventE_EEC2IJSD_ELb0ELb0EEEDpOT_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk15tupleIJOZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS2_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS3_FvRKT_EEUlP6CEventE_EEC2IJSD_ELb0ELb0EEEDpOT_()');
  },

  onLeave(log, retval, state) {
  }
});
