/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk122__compressed_pair_elemIPNS_10__function6__funcIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUliNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE_NSD_ISG_EEFviRKSF_EEELi0ELb0EEC2IRSM_vEEOT_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk122__compressed_pair_elemIPNS_10__function6__funcIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUliNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE_NSD_ISG_EEFviRKSF_EEELi0ELb0EEC2IRSM_vEEOT_()');
  },

  onLeave(log, retval, state) {
  }
});
