/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk112__tuple_implINS_15__tuple_indicesIJLm0EEEEJOZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS4_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS5_FvRKT_EEUlP6CEventE_EEC2IJLm0EEJSG_EJEJEJSF_EEENS1_IJXspT_EEEENS_13__tuple_typesIJDpT0_EEENS1_IJXspT1_EEEENSK_IJDpT2_EEEDpOT3_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk112__tuple_implINS_15__tuple_indicesIJLm0EEEEJOZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS4_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS5_FvRKT_EEUlP6CEventE_EEC2IJLm0EEJSG_EJEJEJSF_EEENS1_IJXspT_EEEENS_13__tuple_typesIJDpT0_EEENS1_IJXspT1_EEEENSK_IJDpT2_EEEDpOT3_()');
  },

  onLeave(log, retval, state) {
  }
});
