/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk15tupleIJONS_9allocatorIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUliNS_12basic_stringIcNS_11char_traitsIcEENS1_IcEEEEE_EEEEC2IJSF_ELb0ELb0EEEDpOT_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk15tupleIJONS_9allocatorIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUliNS_12basic_stringIcNS_11char_traitsIcEENS1_IcEEEEE_EEEEC2IJSF_ELb0ELb0EEEDpOT_()');
  },

  onLeave(log, retval, state) {
  }
});
