/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk110__function6__funcIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS3_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS4_FvRKT_EEUlP6CEventE_NS_9allocatorISE_EEFvSD_EE7destroyEv.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk110__function6__funcIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS3_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS4_FvRKT_EEUlP6CEventE_NS_9allocatorISE_EEFvSD_EE7destroyEv()');
  },

  onLeave(log, retval, state) {
  }
});
