/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk19allocatorIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS0_IcEEEEblmdS0_NS8_14adl_serializerEEEE_EC2INS_10__function6__funcISJ_SK_FvSI_EEEEERKNS0_IT_EE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk19allocatorIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS0_IcEEEEblmdS0_NS8_14adl_serializerEEEE_EC2INS_10__function6__funcISJ_SK_FvSI_EEEEERKNS0_IT_EE()');
  },

  onLeave(log, retval, state) {
  }
});
