/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk122__compressed_pair_elemINS_22__allocator_destructorINS_9allocatorINS_10__function6__funcIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS2_IcEEEEblmdS2_NSC_14adl_serializerEEEE_NS2_ISN_EEFvSM_EEEEEEELi1ELb0EEC2ISS_vEEOT_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk122__compressed_pair_elemINS_22__allocator_destructorINS_9allocatorINS_10__function6__funcIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUlN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS2_IcEEEEblmdS2_NSC_14adl_serializerEEEE_NS2_ISN_EEFvSM_EEEEEEELi1ELb0EEC2ISS_vEEOT_()');
  },

  onLeave(log, retval, state) {
  }
});
