/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk110unique_ptrINS_10__function6__funcIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUliNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE_NSD_ISG_EEFviRKSF_EEENS_22__allocator_destructorINSD_ISL_EEEEEC2ILb1EvEEPSL_NS_16__dependent_typeINS_27__unique_ptr_deleter_sfinaeISO_EEXT_EE20__good_rval_ref_typeE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk110unique_ptrINS_10__function6__funcIZN3sce3rts15SignalingClient4Impl14getProfileInfoENS_8functionIFviEEEEUliNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE_NSD_ISG_EEFviRKSF_EEENS_22__allocator_destructorINSD_ISL_EEEEEC2ILb1EvEEPSL_NS_16__dependent_typeINS_27__unique_ptr_deleter_sfinaeISO_EEXT_EE20__good_rval_ref_typeE()');
  },

  onLeave(log, retval, state) {
  }
});
