/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk112__tuple_leafILm0ERKNS_9allocatorIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS3_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS4_FvRKT_EEUlP6CEventE_EELb0EEC2ISH_vEEOS7_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt6__ndk112__tuple_leafILm0ERKNS_9allocatorIZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS3_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS4_FvRKT_EEUlP6CEventE_EELb0EEC2ISH_vEEOS7_()');
  },

  onLeave(log, retval, state) {
  }
});
