/*
 * Auto-generated by Frida. Please modify to match the signature of _ZZN3sce3rts15SignalingClient4Impl14getProfileInfoENSt6__ndk18functionIFviEEEENUliNS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEE_C2EOSD_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZZN3sce3rts15SignalingClient4Impl14getProfileInfoENSt6__ndk18functionIFviEEEENUliNS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEE_C2EOSD_()');
  },

  onLeave(log, retval, state) {
  }
});
