/*
 * Auto-generated by Frida. Please modify to match the signature of _ZZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS0_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS1_FvRKT_EENKUlP6CEventE_clESA_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZZN3sce5party24GameTitleInfoTransceiver20registerEventHandlerINS0_49UserProfileEventMyGameTitleInfoOnPsnServerUpdatedEEEvMS1_FvRKT_EENKUlP6CEventE_clESA_()');
  },

  onLeave(log, retval, state) {
  }
});
