/*
 * Auto-generated by Frida. Please modify to match the signature of _ZZN3sce3rts15SignalingClient4Impl14getProfileInfoENSt6__ndk18functionIFviEEEENUlN8nlohmann10basic_jsonINS3_3mapENS3_6vectorENS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEblmdSE_NS7_14adl_serializerEEEE_D2Ev.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZZN3sce3rts15SignalingClient4Impl14getProfileInfoENSt6__ndk18functionIFviEEEENUlN8nlohmann10basic_jsonINS3_3mapENS3_6vectorENS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEblmdSE_NS7_14adl_serializerEEEE_D2Ev()');
  },

  onLeave(log, retval, state) {
  }
});
