/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN16dng_image_writer20WriteTIFFWithProfileER8dng_hostR10dng_streamRK9dng_imagejjPK12dng_metadataPKvjPK14dng_resolutionPK16dng_jpeg_previewPK16dng_memory_block19dng_metadata_subset.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN16dng_image_writer20WriteTIFFWithProfileER8dng_hostR10dng_streamRK9dng_imagejjPK12dng_metadataPKvjPK14dng_resolutionPK16dng_jpeg_previewPK16dng_memory_block19dng_metadata_subset()');
  },

  onLeave(log, retval, state) {
  }
});
