/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK12dng_negative27ComputeCameraProfileToEmbedERK12dng_metadata.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK12dng_negative27ComputeCameraProfileToEmbedERK12dng_metadata()');
  },

  onLeave(log, retval, state) {
  }
});
