/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android38legacy2aidl_audio_profile_AudioProfileERK13audio_profileb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android38legacy2aidl_audio_profile_AudioProfileERK13audio_profileb()');
  },

  onLeave(log, retval, state) {
  }
});
