/*
 * Auto-generated by Frida. Please modify to match the signature of _Z15SetTaskProfilesiSt16initializer_listINSt3__117basic_string_viewIcNS0_11char_traitsIcEEEEEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_Z15SetTaskProfilesiSt16initializer_listINSt3__117basic_string_viewIcNS0_11char_traitsIcEEEEEb()');
  },

  onLeave(log, retval, state) {
  }
});
