/*
 * Auto-generated by Frida. Please modify to match the signature of _Z18SetProcessProfilesjiNSt3__14spanIKNS_17basic_string_viewIcNS_11char_traitsIcEEEELm18446744073709551615EEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_Z18SetProcessProfilesjiNSt3__14spanIKNS_17basic_string_viewIcNS_11char_traitsIcEEEELm18446744073709551615EEE()');
  },

  onLeave(log, retval, state) {
  }
});
