/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN18ApplyProfileAction19DropResourceCachingEN13ProfileAction17ResourceCacheTypeE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN18ApplyProfileAction19DropResourceCachingEN13ProfileAction17ResourceCacheTypeE()');
  },

  onLeave(log, retval, state) {
  }
});
