/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN12TaskProfiles18SetProcessProfilesINSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEEEbjiNS1_4spanIKT_Lm18446744073709551615EEEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN12TaskProfiles18SetProcessProfilesINSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEEEbjiNS1_4spanIKT_Lm18446744073709551615EEEb()');
  },

  onLeave(log, retval, state) {
  }
});
