/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK11TaskProfile13ExecuteForUIDEj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK11TaskProfile13ExecuteForUIDEj()');
  },

  onLeave(log, retval, state) {
  }
});
