/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK12TaskProfiles10GetProfileENSt3__117basic_string_viewIcNS0_11char_traitsIcEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK12TaskProfiles10GetProfileENSt3__117basic_string_viewIcNS0_11char_traitsIcEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
