/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK15SetCgroupAction11UseCachedFdEN13ProfileAction17ResourceCacheTypeEi.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK15SetCgroupAction11UseCachedFdEN13ProfileAction17ResourceCacheTypeEi()');
  },

  onLeave(log, retval, state) {
  }
});
