/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK15WriteFileAction16WriteValueToFileERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEN13ProfileAction17ResourceCacheTypeEjib.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK15WriteFileAction16WriteValueToFileERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEN13ProfileAction17ResourceCacheTypeEjib()');
  },

  onLeave(log, retval, state) {
  }
});
