/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK15WriteFileAction11UseCachedFdEN13ProfileAction17ResourceCacheTypeERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK15WriteFileAction11UseCachedFdEN13ProfileAction17ResourceCacheTypeERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
