/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4bssl19SSL_decline_handoffEP6ssl_st.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4bssl19SSL_decline_handoffEP6ssl_st()');
  },

  onLeave(log, retval, state) {
  }
});
