/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4bssl17SSL_apply_handoffEP6ssl_stNS_4SpanIKhEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4bssl17SSL_apply_handoffEP6ssl_stNS_4SpanIKhEE()');
  },

  onLeave(log, retval, state) {
  }
});
