/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4bssl21SSL_serialize_handoffEPK6ssl_stP6cbb_stP22ssl_early_callback_ctx.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4bssl21SSL_serialize_handoffEPK6ssl_stP6cbb_stP22ssl_early_callback_ctx()');
  },

  onLeave(log, retval, state) {
  }
});
