/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4bssl35SSL_set_aes_hw_override_for_testingEP6ssl_stb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4bssl35SSL_set_aes_hw_override_for_testingEP6ssl_stb()');
  },

  onLeave(log, retval, state) {
  }
});
