/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4bssl24SSL_CTX_set_handoff_modeEP10ssl_ctx_stb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4bssl24SSL_CTX_set_handoff_modeEP10ssl_ctx_stb()');
  },

  onLeave(log, retval, state) {
  }
});
