/*
 * Auto-generated by Frida. Please modify to match the signature of d2i_SSL_SESSION_bio.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('d2i_SSL_SESSION_bio()');
  },

  onLeave(log, retval, state) {
  }
});
