/*
 * Auto-generated by Frida. Please modify to match the signature of ERR_load_SSL_strings.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('ERR_load_SSL_strings()');
  },

  onLeave(log, retval, state) {
  }
});
