/*
 * Auto-generated by Frida. Please modify to match the signature of i2d_SSL_SESSION.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`i2d_SSL_SESSION(in=${args[0]}, *pp=${args[1]})`);
  },

  onLeave(log, retval, state) {
  }
});
