/*
 * Auto-generated by Frida. Please modify to match the signature of OPENSSL_init_ssl.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`OPENSSL_init_ssl(opts=${args[0]}, settings=${args[1]})`);
  },

  onLeave(log, retval, state) {
  }
});
