/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_load_client_CA_file.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_load_client_CA_file(file="${args[0].readUtf8String()}")`);
  },

  onLeave(log, retval, state) {
  }
});
