/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_get_shared_ciphers.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_get_shared_ciphers(s=${args[0]}, buf="${args[1].readUtf8String()}", size=${args[2]})`);
  },

  onLeave(log, retval, state) {
  }
});
