/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_set_tlsext_status_ocsp_resp.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_set_tlsext_status_ocsp_resp(ssl=${args[0]}, resp=${args[1]}, len=${args[2]})`);
  },

  onLeave(log, retval, state) {
  }
});
