/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_CTX_use_PrivateKey_ASN1.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_CTX_use_PrivateKey_ASN1(pk=${args[0]}, ctx=${args[1]}, d=${args[2]}, len=${args[3]})`);
  },

  onLeave(log, retval, state) {
  }
});
