/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_select_next_proto.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_select_next_proto(*out=${args[0]}, outlen=${args[1]}, server=${args[2]}, server_len=${args[3]}, client=${args[4]}, client_len=${args[5]})`);
  },

  onLeave(log, retval, state) {
  }
});
