/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_SESSION_get0_id_context.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_SESSION_get0_id_context(s=${args[0]}, len=${args[1]})`);
  },

  onLeave(log, retval, state) {
  }
});
