/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_set0_wbio.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_set0_wbio(s=${args[0]}, wbio=${args[1]})`);
  },

  onLeave(log, retval, state) {
  }
});
