/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_set_session_id_context.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_set_session_id_context(ssl=${args[0]}, sid_ctx=${args[1]}, sid_ctx_len=${args[2]})`);
  },

  onLeave(log, retval, state) {
  }
});
