/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_get_ex_data_X509_STORE_CTX_idx.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('SSL_get_ex_data_X509_STORE_CTX_idx()');
  },

  onLeave(log, retval, state) {
  }
});
