/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_set_alpn_protos.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_set_alpn_protos(ssl=${args[0]}, protos=${args[1]}, protos_len=${args[2]})`);
  },

  onLeave(log, retval, state) {
  }
});
