/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_CTX_load_verify_locations.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_CTX_load_verify_locations(ctx=${args[0]}, CAfile="${args[1].readUtf8String()}", CApath=${args[2]})`);
  },

  onLeave(log, retval, state) {
  }
});
