/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_SESSION_get_master_key.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_SESSION_get_master_key(session=${args[0]}, out=${args[1]}, outlen=${args[2]})`);
  },

  onLeave(log, retval, state) {
  }
});
