/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_CTX_use_psk_identity_hint.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_CTX_use_psk_identity_hint(ctx=${args[0]}, hint="${args[1].readUtf8String()}")`);
  },

  onLeave(log, retval, state) {
  }
});
