/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_export_keying_material.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_export_keying_material(s=${args[0]}, out=${args[1]}, olen=${args[2]}, label=${args[3]}, llen=${args[4]}, context=${args[5]}, contextlen=${args[6]}, use_context=${args[7]})`);
  },

  onLeave(log, retval, state) {
  }
});
