/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_CIPHER_standard_name.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_CIPHER_standard_name(cipher=${args[0]})`);
  },

  onLeave(log, retval, state) {
  }
});
