/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_SESSION_set1_id.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_SESSION_set1_id(s=${args[0]}, sid=${args[1]}, sid_len=${args[2]})`);
  },

  onLeave(log, retval, state) {
  }
});
