/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_add_file_cert_subjects_to_stack.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_add_file_cert_subjects_to_stack(STACK_OF(X509_NAME=${args[0]})`);
  },

  onLeave(log, retval, state) {
  }
});
