/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_get_shared_sigalgs.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`SSL_get_shared_sigalgs(s=${args[0]}, idx=${args[1]}, psign=${args[2]}, phash=${args[3]}, psignhash=${args[4]}, rsig=${args[5]}, rhash=${args[6]})`);
  },

  onLeave(log, retval, state) {
  }
});
