/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android38aidl2legacy_AudioProfile_audio_profileERKNS_5media5audio6common12AudioProfileEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7android38aidl2legacy_AudioProfile_audio_profileERKNS_5media5audio6common12AudioProfileEb()');
  },

  onLeave(log, retval, state) {
  }
});
